name:                LCom
version:             0.1.0.0
github:              "ShapeOfMatter/LCom"
license:             BSD3
author:              "Mako Bates"
maintainer:          "Mako.Bates@uvm.edu"
copyright:           "2021 Mako Bates"

extra-source-files:
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ShapeOfMatter/LCom#readme>

ghc-options: 
    - "-fplugin=Polysemy.Plugin"
    - "-Wall"
    - "-O2"

default-extensions:
    - AllowAmbiguousTypes
    - DataKinds
    - FlexibleContexts
    - FlexibleInstances
    - FunctionalDependencies
    - GADTs
    - GeneralizedNewtypeDeriving
    - LambdaCase
    - MultiParamTypeClasses
    - PolyKinds
    - RankNTypes
    - ScopedTypeVariables
    - TemplateHaskell
    - TypeApplications
    - TypeOperators
    - TypeFamilies
    - UndecidableInstances

dependencies:
- base >= 4.7 && < 5
  #- cereal >= 0.5.8
- constraints >= 0.13
  #- cryptonite >= 0.29
- distributive >= 0.5.3 && < 0.7
- fin >= 0.2
- gdp >= 0.0.3.0
  #- mtl >= 2.2.2
- polysemy >= 1.4  
  #- polysemy-zoo >= 0.7
- polysemy-plugin >= 0.3
  #- QuickCheck >= 2.14
  #- random >= 1.2
  #- statistics >= 0.15
  #- Stream >= 0.4.7
- type-level-sets >= 0.8.9.0
- vec >= 0.4

library:
  source-dirs: src

executables:
  LCom-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LCom

tests:
  LCom-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LCom
