name:                LCom
version:             0.1.0.0
github:              "ShapeOfMatter/LCom"
license:             BSD3
author:              "Mako Bates"
maintainer:          "Mako.Bates@uvm.edu"
copyright:           "2021 Mako Bates"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ShapeOfMatter/LCom#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  LCom-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LCom

tests:
  LCom-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LCom
